# This playbook will validate exports on fsx and mount those with the /etc/fstab file.

- hosts: "{{ variable_host | default('role_node_centos') }}"
  remote_user: "{{ variable_user | default('centos') }}"
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true
  vars_files:
    - /deployuser/ansible/group_vars/all/vars
    - vars/main.yml

  vars:
    import_pool: true
    variable_user: centos
    
    fsx_ip: # this should be provided inline since it is unique on each tf apply
    # ansible_become_pass: "{{ user_deadlineuser_pw }}"
    pcoip: false

  roles:
  - role: firehawkvfx.fsx.fsx_volume_mounts
  - role: firehawkvfx.onsite_nfs.onsite_nfs_share
    when: localnas1_private_ip != 'none'